### ISSUE TITLE
Time sheet: Create new form better suited for smaller viewports

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6003] opened 2019-04-17 00:16 UTC
The table is not responsive and breaks on smaller devices.

We should keep the table for larger devices, and add a media query that targets smaller devices and shows a simpler form instead of the current table.

**Comment by a17fellu** [comment] 2019-04-24 08:12
What is file is this referring to?

**Comment by a17joaap** [comment] 2019-04-24 10:11
The time sheet table in daily-minutes.js
![final](https://user-images.githubusercontent.com/37792198/56651714-fa747680-6689-11e9-93ee-61be75b66061.PNG)

**Comment by a17fellu** [comment] 2019-04-24 13:56
Working on a fix for this now on branch: https://github.com/HGustavs/LenaSYS/tree/gruppC2019W18_6003.

Have made it a lot better but it still breaks for smaller screens. The problem is that to be able to fix it completely, a lot of refactoring needs to be done. So 2 options:

* Make a pull Request based on how the fix is right now and don't care that it still breaks on the smallest screens. Then the least amount of refactoring will be done.

* Refactor more to fix it for smaller screens (Unadvised)

**Comment by a17joaap** [comment] 2019-04-24 14:16
I took a look, and I don't think percentages are the way to go here. It looks really weird on bigger screens.
I think we could do it better with media queries to serve both bigger screens and smaller.

http://jsfiddle.net/uzsw7s4o/

Something like that maybe?

If refactoring is needed, I say go for it. The time sheet table was created like two weeks ago so refactoring it wont break anything.

**Comment by a17joaap** [comment] 2019-04-24 15:24
After looking at the problem a bit more, small devices just don't seem to like tables very much.

One idea would be to wrap the current table in a div that only shows on bigger devices, and have a completely different form for mobile. Like:

Date:                   (date input)
Type:                   (type input)
Reference:           (ref input)
Comment:           (comment input)
[Submit button]

**Comment by a17fellu** [comment] 2019-04-24 15:26
Totally agree. Ok refactoring it is.

**Comment by a17fellu** [comment] 2019-04-24 15:30
I think that is a better option. Maybe should create a new issue for adding a different form when on mobile?

**Comment by a17joaap** [comment] 2019-04-24 16:26
We could close this and create that, or just rename this one

**Comment by a17fellu** [comment] 2019-04-25 13:14
Made it so the current form disappears and instead shows the smallerViewportForm div when the window width gets below 1120px.

When window width is > 1120px:
![computerform](https://user-images.githubusercontent.com/49202955/56738066-151f1c00-676c-11e9-837e-afe5043cafaa.PNG)

When window width <1120px:
![mobileform](https://user-images.githubusercontent.com/49202955/56738144-4992d800-676c-11e9-9eb9-75fa2acda6f8.PNG)

Will start creating the new form on branch:
https://github.com/HGustavs/LenaSYS/tree/gruppC2019W18_6003

**Comment by a17fellu** [comment] 2019-04-26 13:31
Working on the form for smaller Viewports this is how it looks like now:
![form for smaller devices](https://user-images.githubusercontent.com/49202955/56810996-04d47300-6838-11e9-9ac5-1ccdf7ff66e3.PNG)

**Next step is to build the form through JavaScript since i at the moment have it on daily-minutes.html**

**Comment by a17joaap** [comment] 2019-04-26 14:51
Looks good!

**Comment by a17maxsj** [comment] 2019-04-29 08:36
Nice!

**Comment by a17maxsj** [comment] 2019-04-30 11:41
Creating a new issue for the mobile view, continuing the work there

**Comment by a17fellu** [comment] 2019-05-01 22:42
Closing since Pull Request #6483 fixes this

**Closed by a17fellu** 2019-05-01 22:42 UTC
Labels: gruppC2019
