### ISSUE TITLE
Implement test file for showDuggaservice.php

### ISSUE THREAD

**Issue by d21erisu** [HGustavs/LenaSYS#13860] opened 2023-05-08 13:26 UTC
Related to: #13847

You can found a guide on how to use this API [here](https://github.com/HGustavs/LenaSYS/blob/cdb827478334ec6099763471afd3e0c16ade1332/Shared/Documentation/Test%20API/Guide%20on%20how%20to%20use%20Test%20API.md).

**Comment by d21erisu** [comment] 2023-05-25 09:10
The pull request gets merged but it's not complete. This because it's the last day of the project.

**Comment by a22albjo** [comment] 2024-04-03 12:06
Extracted from parent issue:
With the help of the newly implemented [Test API](https://github.com/HGustavs/LenaSYS/blob/g2-2023-v5/Shared/test.php) every service can now be tested automatically, for example a course can be created with the help of this Test API instead of doing it manually. You can find a guide on how to use this API [here](https://github.com/HGustavs/LenaSYS/blob/cdb827478334ec6099763471afd3e0c16ade1332/Shared/Documentation/Test%20API/Guide%20on%20how%20to%20use%20Test%20API.md).

**Remember that all tests should be executed on a separate database!**

With the help of this guide all service files should have a __(******service_test.php)__ located here: https://github.com/HGustavs/LenaSYS/tree/g2-2023-v5/DuggaSys/tests

**Comment by a22albjo** [comment] 2024-04-03 12:14
> This issue seem to have almost been resolved, this comment was added:
> Overall you need to add username and password to certain tests to align with the pre-requisites. For example if pre-req !=issuperuser, or if pre-req == issuperuser. These need to be added in the sends as username and password to match the pre-reqs.
> 

It then seems like the developer got to work and solved the issue above in a few places but something was missing, this is the last comment before it was merged and the students where done with the course: 

> Username and password still missing from a few sends to match pre-req

I will begin to identify where the username and password is missing and add them.

Then review the code and see if it seems fine as a whole.

**Comment by a22albjo** [comment] 2024-04-03 14:05
We can run the tests from:
http://localhost/LenaSYS/DuggaSys/tests/
All tests seem to be full of errors and warnings.

**Comment by a22albjo** [comment] 2024-04-04 06:37
@a22iliru I think that a issue to change the references to services from absolute to relative paths is needed to make [duggaedservice-tests.php](http://localhost/LenaSYS/DuggaSys/tests/duggaedservice-tests.php) work.

**Comment by a22albjo** [comment] 2024-04-04 06:42
@a22iliru I find that the same thing is true for filedservice.php.

Example:
row 8
`
		'service' => 'https://cms.webug.se/root/G2/students/b21kurar/LenaSYS/DuggaSys/fileedservice.php',
`
should be changed to:
`
		'service' => 'fileedservice.php',
`
This are two good first issues for someone that might be struggling with their first issue.

**Comment by a22albjo** [comment] 2024-04-04 08:13
The tests is a bit of a mess, this will be a legthy issue, it seems that there is a problem with test.php where $QueryReturnJSONbefore is defined after it is itterated over and that there is an issue with the testdata that makes test.php look for testdata where there is none, the username and password is missing the first time the test is done but not the next time.

Here are the warnings and errors:

> Warning: Undefined variable $QueryReturnJSONbefore in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 129
> 
> Warning: foreach() argument must be of type array|object, null given in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 129
> 
> Warning: Undefined variable $QueryReturnJSONbefore in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 129
> 
> Warning: foreach() argument must be of type array|object, null given in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 129
> 
> Warning: Undefined array key "variables-query-before-test-1" in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 57
> 
> Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 58
> 
> Warning: Undefined variable $pdo in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 63
> 
> Warning: Undefined array key "username" in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 171
> 
> Warning: Undefined array key "password" in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 171
> 
> Warning: Undefined variable $queryReturnPathAndDataJSON in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 331
> 
> Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php:57 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php(188): doDBQuery('DELETE FROM gro...', 'UNK', 'UNK', 'UNK') #1 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/tests/showDuggaservice_test.php(241): testHandler(Array, false) #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 57

**Comment by a22albjo** [comment] 2024-04-09 05:04
Waiting for pull request #14396 to get merged to continue the work with this issue.

**Comment by a22albjo** [comment] 2024-04-09 05:08
Findings: 

- We need to change URL to the services to make the tests work.

- We need to use quotes around the selectors in quary before test.

- We need to remove duplicate entries in to the database to make the quary be able to run multiple times without a flushed database.

**Comment by a22albjo** [comment] 2024-04-10 12:47
Test: 'get data from userAnswer (student)'
Had this query: 
`'query-before-test-3' => "SELECT MAX(lid) FROM listentries",`
to populate this variable:             
`'moment' => '<!query-before-test-3!><*[0][listentries]*>'`

This don't work for a few reasons, i have found that the selector should be inside quotes and i need to change the key to make test.php find the value. We seem to have a problem with test.php expect an array on line 

Test: 'get data from userAnswer (student)'
Has this query: `'query-before-test-3' => "SELECT MAX(lid) AS listentries FROM listentries",`
to populate this variable:             `'moment' => '<!query-before-test-3!><*[0]["listentries"]*>'`
something still goes wrong in test.php. I can see that up to line 145 everything seems fine.

**Comment by a22albjo** [comment] 2024-04-10 13:47
After a lot of testing i still end up with a few errors:
```
Warning: Undefined variable $variablesArray in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 84

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php:84 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php(132): doDBQuery(Object(PDOStatement), Array, Array, 'query-before-te...') #1 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/tests/showDuggaservice_test.php(241): testHandler(Array, true) #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/Shared/test.php on line 84
```

**Comment by a22albjo** [comment] 2024-04-10 13:48
The code gets stuck here:
        if (strpos($queryString, '?') !== false) {
            for ($i = 0; $i < count($variablesArray); $i++) {
                $variableToUse = $data[$variablesArray[$i]];
                $query->bindParam($i+1, $variableToUse);
            }
        }

**Comment by a22albjo** [comment] 2024-04-11 08:11
Its unclear to mig right now exactly what all the different tests mean and it is very difficult to get an understanding for the expected output on all the tests. I will split this issue up into one issue per test to make the problem more approachable.

**Comment by a22albjo** [comment] 2024-04-11 10:59
I will create one issue per test, all the tests has commented out versions more or less finished in showDuggaservice.php, to resolve these issues gather expected output from the service and make the test work as intended:
Get active users
Create active users
update active users
get data from userAnswer (student)
get data from userAnswer (teacher)
update submitted dugga
submit dugga
super-view data from useranswer on hash (teacher)
super-view data from useranswer on moment (teacher)
super-view data on quizname (teacher)
view data on userAnswer (teacher)
super-view data on quizname (teacher)

**Closed** 2024-04-11 12:52 UTC
Labels: Group-2-2023
