### ISSUE TITLE
Section editor refactoring bug from project course 2020

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9870] opened 2021-04-07 10:27 UTC
The project course in 2020 broke the no refactoring rule in an incompatible manner.

Version 0.12 (before project 2020 version) works well evidenced by screenshot below

<img width="987" alt="Screenshot 2021-04-07 at 12 22 04" src="https://user-images.githubusercontent.com/6978801/113851638-ff119700-979b-11eb-98c4-3d4e0a2f45dd.png">

With the same data the startup project 2021 version does not work

<img width="899" alt="Screenshot 2021-04-07 at 12 22 18" src="https://user-images.githubusercontent.com/6978801/113851731-18b2de80-979c-11eb-9ff8-08fbc34d073f.png">

It seems like a new incompatible column "tabs" was added to the database to store the existing tabs data in a new place.

This makes the application completely incompatible with existing installations (which is the whole purpose of LenaSYS) ...

Previously the tab count was stored in the gradesys column (since an element can not be both tabbed and have a grade at the same time). We must revert this change so that the tabs are once again read and stored in the gradesys column.

**Comment by HGustavs** [comment] 2021-04-07 10:27
This makes testing against existing installations impossible so it has rather high priority.

**Comment by HGustavs** [comment] 2021-04-07 10:36
I updated the following code on line 552 in sectionedservice and I got the following messaage

```
if(!$query->execute()) {
	$error=$query->errorInfo();
	$debug="Error reading entries\n".$error[2]."\nRow number ".__LINE__;
}
```

<img width="363" alt="Screenshot 2021-04-07 at 12 35 40" src="https://user-images.githubusercontent.com/6978801/113853323-d38fac00-979d-11eb-9439-f531ff1919ba.png">

So I am confident that the problem is partially located in those lines

**Comment by HGustavs** [comment] 2021-04-07 10:45
So a partial fix can be done by updating the SQL along the following lines

$query = $pdo->prepare("SELECT lid,moment,entryname,pos,kind,link,visible,code_id,listentries.gradesystem,highscoremode,deadline,qrelease,comments, qstart, jsondeadline, groupKind,listentries.gradesystem as tabs, feedbackenabled, feedbackquestion FROM listentries LEFT OUTER JOIN quiz ON listentries.link=quiz.id WHERE listentries.cid=:cid and listentries.vers=:coursevers ORDER BY pos");

**Comment by HGustavs** [comment] 2021-04-07 10:47
This allows us to at least see the old courses.

However the rendering of tabs seems to be one step off... compared to the view at the top

<img width="1056" alt="Screenshot 2021-04-07 at 12 45 52" src="https://user-images.githubusercontent.com/6978801/113854605-56653680-979f-11eb-9995-86f287db23c8.png">

One too many tabs are added... so the tab rendering code needs to be fixed so that the correct number of tabs are added.

**Comment by HGustavs** [comment] 2021-04-07 10:58
However the saving of the tabs into the gradesys column also needs to be added so that we can change the number of tabs without SQL errors... as we get currently since it tries to store the tab number in the tabs column rather than in the correct gradesys column...

To test correct saving and reading of tabs run the following code

```
ALTER TABLE listentries DROP COLUMN tabs;
```
If we can edit (and display) the tabs normally, without the tabs column, this bug can be retired

**Comment by HGustavs** [comment] 2021-04-07 11:55
...Hopefully this is the only refactoring bug that is found from 2020...

**Comment by b18phika** [comment] 2021-04-07 12:13
@HGustavs We're having trouble reproducing your error. We've managed to create a new course version and selecting it in the dropdown. We can see the already existing versions and the one that we created, so three in total.

**Comment by HGustavs** [comment] 2021-04-07 20:46
It is a problem with the rendering of course entries i.e. the section editor

The problem is that for the year 2020 in the project course it seems like the students added a column for "tabs", which previously was stored in "gradesys".

This is refactoring and is incompatible with existing courses since existing courses store the tab number in the gradesys column.

Since older versions of the data does not have the column the easiest way to test for the bug is removing that column (as it is in the existing installations).

So what we need is to revert back that change, and storing the tab count in the gradesys column again. We must make sure that we do not allow storing of a tab count when we actually need the gradesys (moment i.e. delkurs)

**Comment by HGustavs** [comment] 2021-04-07 20:49
The most common way to solve added columns is to add an empty column with that name for existing data.

If we just add an empty column tabs to existing courses, we effectively remove all tabs in all existing courses (and all previous iterations of a course) which for obvious reasons is unacceptable. So we are required to mitigate the effects of that refactoring.

**Comment by b18phika** [comment] 2021-04-09 12:02
We have now pushed a partial fix for this issue on branch G2-2021-W15-ISSUE#9870. We haven't opened a pull request yet, as we haven't fixed the following part yet: 

> We must make sure that we do not allow storing of a tab count when we actually need the gradesys (moment i.e. delkurs) as this would over-write the gradesys value.

As we simply haven't been able to figure out when gradesys is needed or not. 

We're also having trouble testing this issue as we haven't been able to replicate the error ourselves.

**Comment by HGustavs** [comment] 2021-04-12 15:19
if you run the code

```
ALTER TABLE listentries DROP COLUMN tabs;
```

you are at the same state as any running server (which do not have that column) so I would start there.

Without this column no errors should happen.

Have you removed this column and no errors occur?

**Comment by HGustavs** [comment] 2021-04-12 15:25
So:

Step 1 Remove tab column (we can never change behavior of existing column due to refactoring rule)
Step 2 Make sure tabs are read from gradesys column
Step 3 Store tab count in gradesys column on update
Step 4 fix inserts so no tabs column is used

Step 3b Make sure we do _not_ store tabs in gradesys coulmn for "moment" object since they use gradesys to store the grade system for that "moment".

**Comment by b18phika** [comment] 2021-04-13 09:32
@HGustavs We believe to have now fixed the issue, as per your step-by-step instructions. However, we haven't opened a pull request, Since it might be hard for us to test, we thought it might be a good idea for you to look it over first.

**Comment by a20chrjo** [comment] 2021-04-19 12:34
Approved and merged by @a20chrjo

**Closed by a20chrjo** 2021-04-19 12:34 UTC
Labels: Bug, Group-2-2021, High priority
