### ISSUE TITLE
Fileed:  removes function button not work properly!

### ISSUE THREAD

**Issue by a16hiwah** [HGustavs/LenaSYS#6935] opened 2019-05-13 09:09 UTC
![bild](https://user-images.githubusercontent.com/37792852/57609585-7d913a00-756f-11e9-9aa7-692c7b91f056.png)

**Comment by HGustavs** [comment] 2019-05-13 09:59
We are not allowed to remove all files... I think it should not remove files that have been linked.

Perhaps some kind of error message happens?

Unclear if it is a bug or the expected behavior.

We do not want to delete a linked file by accident.

**Comment by b17timjo** [comment] 2019-05-14 11:33
@HGustavs is a reasonable implementation to show a "deactivated" button (wastebasket with a red line over, or something) for files which are used somewhere in the system (if that can even be determined...) and only show the regular wastebasket with deletion functionality when the file in question is not used anywhere?

**Comment by HGustavs** [comment] 2019-05-17 07:04
I am not sure it is easy to know if a file is used... I dont mind if the button kinda sorta works.

**Comment by HGustavs** [comment] 2019-05-17 07:05
Perhaps an informative error message that the file is in use?

**Comment by b17timjo** [comment] 2019-05-17 08:51
To reiterate the information: it should not be possible to remove a file which is in use anywhere in the system -- removal must never cause a 404 somewhere else.

Unless an implementation can guarantee the functionality above, the button should not remove anything.

**Comment by b17nicsv** [comment] 2019-05-20 12:12
At the very least it should give a informative error message, saying that the file is used somewhere.

**Comment by a17pongo** [comment] 2019-05-22 07:21
So after doing some research into this issue, it seems like there does not exist, at the moment, a possible way to indicate if a file is used elsewhere. The only way to keep track on files is through what kind they are and go from there. 
One more problem is that while deleting, there is no functionality for actually removing files stored from the filesystem and also removing the link from the database does not work properly either.

One possible solution could be that you are only allowed to remove course local files.
Thoughts on this? @HGustavs @b17nicsv @b17timjo

**Comment by a17pongo** [comment] 2019-05-22 11:30
Started creating sub issues for this as the problem appears to be quite big.
ref:
#7389
#7388

**Comment by a18felen** [comment] 2020-04-27 10:33
What exactly is the issue in this case? If its the fact that the trashcan does nothing when showing? If that is the issue it was most likely because the user lacked permissions to remove the file but the button would still be displayed. That has been fixed by only showing the trashcan if the person has permissions to actually remove the file. 

If the issue is that it actually did not remove it from the database or the file that has been fixed. Not sure why this is still open. 

And if its an issue that you should prevent someone from deleting a file when its in use then there is an issue for already that is more clear what the issue is #7478 

So should this issue be closed @HGustavs  @a97marbr?

**Comment by a18jenro** [comment] 2020-05-18 06:26
Not sure either what the issue is, now one cannot delete files that are used in a code example: https://github.com/HGustavs/LenaSYS/issues/7478
So I think this issue is solved.

If anyone disagrees, please reopen the issue and clarify.

**Closed by a18jenro** 2020-05-18 06:26 UTC
Labels: File Editor, Grupp 3 - 2020
