### ISSUE TITLE
When hovering over an empty cell highlightcolumn is too short

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2431] opened 2016-12-13 20:56 UTC
As title suggests.

Hovering over an empty cell in the resulted will generate a too short highlight border.

**Comment by c14emian** [comment] 2017-03-30 11:22
Not sure what the issue is, can't see anything wrong.

**Comment by a15freed** [comment] 2017-04-06 07:18
We cant find anything about this issue maybe we can close it? @HGustavs @a97marbr

**Closed** 2017-04-19 08:19 UTC
Labels: Group-3
