### ISSUE TITLE
Download all files as zip

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7765] opened 2020-03-23 21:56 UTC
We want the ability for teachers/administrators to download all files from a course.

A download all files menu option in the top toolbar.

**Comment by HGustavs** [comment] 2020-04-01 14:03
not all hand-ins but all files i.e code examples etc for active version of course.

**Comment by b18phibe** [comment] 2020-04-01 14:07
> not all hand-ins but all files i.e code examples etc for active version of course.

Are they group in any special way in the database or where can i find those files?

**Comment by HGustavs** [comment] 2020-04-01 17:16
I would test, to see where they end up by uploading a file...

but as far as I remember there is a folder "downloads" or something to that effect, either in the lenasys root or in shared (it has been in more than one place historically).

And in that folder  there is a folder for each course and inside that a folder for each version of a course.

**Comment by HGustavs** [comment] 2020-04-01 17:17
and in that folder the files are stored one by one.

**Comment by a18jonpe** [comment] 2020-04-02 08:52
There is a folder install/courses that contains two folders, one of which (1) contains the files from the course with ID 1. But other courses are missing. Uploading files does not work either, it redirects to http://localhost/LenaSYS/DuggaSys/filereceive.php but gets stuck there.

**Comment by a18petha** [comment] 2020-04-06 08:11
Cannot reproduce the test, I found the download icon for each course but it seemingly does nothing. The test has been carried out on chrome and firefox, from what I can tell none of the code that has been implemented has been fired once the user interacts with the new download icon

Following code is what I assume to errorhandlers, but I never interacted with these html messages.

![image](https://user-images.githubusercontent.com/49141878/78536471-30086600-77ee-11ea-931a-7ff811561b27.png)

**Comment by a18kaswi** [comment] 2020-04-08 14:29
Closing PR for weekly, https://github.com/HGustavs/LenaSYS/pull/7845

This stil needs to be fixed.

**Comment by a18kaswi** [comment] 2020-04-08 14:29
Oops to fast on the triggerfinger.

**Closed** 2020-04-16 15:52 UTC
Labels: G42020, a18jonpe, b18phibe
