### ISSUE TITLE
Linefeed / Carriage Return Issues

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1801] opened 2015-10-14 11:27 UTC
In the code viewer, files that have double line feeds only count as a single one. The hypothesis is that it is a white space issue. The current fix of adding linefeed space lineffeed is deemed too complicated for some.

When files have line feeds, the line highlighting code says "incorrect line" in an alert, even though the line number is obviously correct. (as it is visible on screen)

PHP Markdown does not support line feeds at all. No line feeds are converted to br tags.

**Comment by a15eriho** [comment] 2017-04-10 08:52
Don't change files, just process the files when viewed in the browser. Maybe replace LF/CR just when viewed.

**Comment by a15jorpa** [comment] 2017-04-12 09:16
Tested with files with multiple linefeeds with no spaces in between, both CRLF and LF, unable to reproduce problem. Example files seem to work fine with hightligting despite containing linefeeds. What PHP markdown are you referring to @HGustavs ?

**Comment by a18kaswi** [comment] 2020-04-20 08:40
Fixed because no answer in five years and we trust studnets three years ago. CLOSING

**Closed by a18kaswi** 2020-04-20 08:40 UTC
Labels: All-Groups, Bug
