### ISSUE TITLE
Registering to seminar - page

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3993] opened 2017-05-17 13:00 UTC
A page needs to be created where students can register for a seminar.

**Comment by HGustavs** [comment] 2017-05-19 08:54
How about:

registration.php
registration.js
registration_service.php

**Comment by a18kaswi** [comment] 2020-04-20 14:57
The files referenses earlier does not exist anymore. I'm assuming the problem is solved and someone forgot to close the issue. Closing.

**Closed by a18kaswi** 2020-04-20 14:57 UTC
Labels: Ideas
