### ISSUE TITLE
Redesign of the ladexport dropdowns

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#7631] opened 2019-05-28 09:55 UTC
![image](https://user-images.githubusercontent.com/37799016/58468888-b4a24680-813e-11e9-8cb4-9f6d84918961.png)

Delkurs,Betygsskala and betygsdatum dropdowns are often mistaken to be filters for the table. Since they are only related to the ladexport content, they should be redesigned.

### Suggestions

- Moving it below the table.
- Seperating it with borders.
- Only having the button ladexport and showing the dropdown in the same popup box below.

![image](https://user-images.githubusercontent.com/37799016/58469195-54f86b00-813f-11e9-998d-4ea5c81b2e67.png)

**Comment by a17robda** [comment] 2019-06-18 10:48
Integrated the LadExport filtering options on the ladexport popup which looks cleaner:

webm:
https://webm.red/2b5M.webm

**Comment by b18jonli** [comment] 2020-04-03 09:18
Duplicate of #7629

**Comment by b18jonli** [comment] 2020-04-06 06:58
Closed bc. duplicate issue

**Closed** 2020-04-06 06:58 UTC
Labels: Group-2-2020, Result Editor, duplicate
