### ISSUE TITLE
Code Viewer: Clean code

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1225] opened 2015-05-04 07:37 UTC
There are a lot of unused functions and variables. By cleaning the code makes it easier to read and understand the code.

**Comment by HGustavs** [comment] 2015-05-04 07:55
In PHP unused is fine if it corresponds to the service.

There should always be variables that correspond to each parameter sent from the client e.g. if the client sends a cid and a version we should have variables for those parameters so that the php correpsonds exactly to what is sent from the client even if it is not used at the moment.

I agree that there is stuff that is not used, particularly in the code viewer javascript.

**Comment by HGustavs** [comment] 2015-05-04 07:57
By the way I think this is a duplicate of issue #464 and issue #465.

It is a good idea to go through the issues from the back and see if there are other duplicates.

**Comment by c12jenek** [comment] 2015-05-11 07:14
Code has been cleaned as much as currently possible, this issue is then solved

**Closed by c12jenek** 2015-05-11 07:14 UTC
Labels: CodeViewer
