### ISSUE TITLE
Filter and sortingdropdowns in navbar bad placement

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6516] opened 2019-05-02 09:39 UTC
The dropdowns have bad placement since some information/options are hidden.

**Comment by a17maxsj** [comment] 2019-05-02 11:41
#6520 has an corresponding image for the same issue, closing this one

**Comment by a17maxsj** [comment] 2019-05-02 11:42
nvm

**Comment by b17nicsv** [comment] 2019-05-03 12:33
Closing this one as it is a duplicate of [Issue 6539](https://github.com/HGustavs/LenaSYS/issues/6593).

**Closed by b17nicsv** 2019-05-03 12:33 UTC
Labels: MergeTest_W19
