### ISSUE TITLE
Create test: super-view data from useranswer on hash in showDuggaservice_test.php

### ISSUE THREAD

**Issue by a22albjo** [HGustavs/LenaSYS#14507] opened 2024-04-11 11:14 UTC
Create test: super-view data from useranswer on hash (teacher) in showDuggaservice_test.php

There is a commented out version of this test more or less finished in showDuggaservice_test.php, to resolve this issue gather expected output from the service and make this test work as intended.

**Comment by a22marca** [comment] 2024-04-24 08:49
one issue with the tests was that the moment field was not retrieved correctly.
This is fixed by adding the following
```
        'query-before-test-3' => "SELECT MAX(lid) AS listentries FROM listentries",
        'variables-query-before-test-4' => "moment",

```
and assigning it like so:
```
        'service-data' => serialize(array( // Data that service needs to execute function
            'hash' => 'dfg4zxc5',
            'username' => 'stei',
            'password' => 'password',
            'moment' => '<!query-before-test-3!><*[0]["listentries"]*>',
        )),
```

**Comment by a22marca** [comment] 2024-04-24 09:02
It seems that even the teacher needs to provide the hash password to be able to access a specific hash. When logged in as a teacher and trying to navigate into a hash, the password input is prompted. 
I will add the hashpwd as a field in the service request.

**Comment by a22marca** [comment] 2024-04-24 09:18
The current issue is that the test returns a response that it is not finding the answer that is inserted into userAnswer before the test. I've narrowed it down to the code block at line 355 in showDuggaservice.php, which is run when variant is not set after retrieving rows from variant and answer. This might because another query needs to be made before the test is run (into variant).

**Comment by a22marca** [comment] 2024-04-24 09:58
I've added a few more queries that are performed before the test, to make sure that the dugga can be found:
```
        'query-before-test-1' => "INSERT INTO course(cid, creator) VALUES (9999, 1);",
        'query-before-test-2' => "INSERT INTO quiz (cid) VALUES (9999)",
        'query-before-test-3' => "SELECT MAX(id) as quizID FROM quiz;",
        'variables-query-before-test-4' => "quizID",
        'query-before-test-4' => "INSERT INTO variant (quizID, variantanswer) VALUES (?, '{Variant}');",
        'query-before-test-5' => "INSERT INTO listentries(cid,entryname,link,kind,pos,creator,visible,vers,gradesystem,highscoremode,feedbackenabled,feedbackquestion) VALUES (9999, 'Inserttobedeleted', 'UNK', 4, 12, 2, 1, 1337, 1, 1, 0, 'UNK');",
        'query-before-test-6' => "SELECT MAX(lid) AS listentries FROM listentries",
        'query-before-test-7' => "SELECT MAX(vid) AS variant FROM variant;",
        'variables-query-before-test-8' => "moment, variant",
        'query-before-test-8' => "INSERT INTO userAnswer(cid,hash,password,moment,variant) VALUES(9999,'dfg4zxc5','password',?,?);",

```

**Comment by a22marca** [comment] 2024-04-24 11:46
Currently the debug output prints this:
```
"Could not find the requested dugga!"
```
This debug is printed in the if-statement at line 88, showDuggaservice.php
```
if($courseid != "UNK" && $coursevers != "UNK" && $duggaid != "UNK" && $moment != "UNK"){
	if((isset($_POST["submission-$courseid-$coursevers-$duggaid-$moment"]) && 
		isset($_POST["submission-password-$courseid-$coursevers-$duggaid-$moment"]) && 
		isset($_POST["submission-variant-$courseid-$coursevers-$duggaid-$moment"]))) {
		$hash=$_POST["submission-$courseid-$coursevers-$duggaid-$moment"];
		$hashpwd=$_POST["submission-password-$courseid-$coursevers-$duggaid-$moment"];
		$variant=$_POST["submission-variant-$courseid-$coursevers-$duggaid-$moment"];
	}
	else{
		$hash=$_SESSION["submission-$courseid-$coursevers-$duggaid-$moment"];
		$hashpwd=$_SESSION["submission-password-$courseid-$coursevers-$duggaid-$moment"];
		$variant=$_SESSION["submission-variant-$courseid-$coursevers-$duggaid-$moment"];
	}
}else{
	$debug="Could not find the requested dugga!";
}
```

I think this debug output can de disregarded since the hash password is already provided as a parameter.

**Comment by a22marca** [comment] 2024-04-24 12:23
I'm trying to determine what the expected-output should be, the problem is that the test is not properly described. So I'm not really sure where the expected-output can be retrieved from the LenaSYS website. Each test has to emulate some sort of action made on the website, but this test is quite hard to understand what it is trying to mirror since there is no description of it.

The test description is "super-view data from useranswer on hash"
and the parameters that was listed at first was:
```
            'hash' => 'dfg4zxc5',
            'username' => 'stei',
            'password' => 'password',
            'moment' => '<!query-before-test-4!><*[0]["listentries"]*>',
```

The description makes me believe this has to do with the "load dugga" button, but the request sent to showDuggaservice.php when going that route also includes the opt "GETPARAM".  That opt is not included in the original test and is not written as a parameter in description in showDuggaservice-test.txt.

"showDuggaservice-test.txt tries to describe the test in some way but it really just says the samething as the original test that was left from last year. It doesn't describe what functionality  is actually being tested on the website.

**Comment by a22marca** [comment] 2024-04-24 12:35
Since we don't know what this should actually test i'm putting this on hold

**Comment by f22linhe** [comment] 2024-04-29 15:40
Updated issue: Fix test 'super-view data from useranswer on hash (teacher)' in showDuggaservice_test.php #15112

**Closed by f22linhe** 2024-04-29 15:40 UTC
Labels: on hold, Group-2-2024
