### ISSUE TITLE
OS settings may make text colour illegible if background colour is set

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5762] opened 2019-04-10 07:14 UTC
Some browsers on some OS:s may use the system default colours to render both background and foreground colours, which may cause illegible colour combinations if only one of those are set.

Example of both colours being set, which is fine:
![textwithcolour](https://user-images.githubusercontent.com/38911528/55858456-0c292a80-5b70-11e9-873f-59e362f616ae.png)

Example of neither being set (in the buttons) which is fine, and also of only background being set (the labels above the buttons) which causes it to be illegible:
![font_visibility](https://user-images.githubusercontent.com/38911528/55858462-0e8b8480-5b70-11e9-955d-368ecc9db494.png)

**Comment by HGustavs** [comment] 2019-04-10 07:31
I would try to set the colors so that it would appear the same as the other dialogs.

**Comment by c17johha** [comment] 2019-04-29 08:41
@c17alepe was not able to reproduce this

**Comment by a16hiwah** [comment] 2019-05-06 07:25
@b17timjo  I tested it on different types of systems OS and got the following result! Maybe this is not a issue?

![os_ok](https://user-images.githubusercontent.com/37792852/57211509-cdf12080-6fe0-11e9-9b39-d14aa0dd18b0.PNG)

**Comment by b17timjo** [comment] 2019-05-06 07:34
@a16hiwah on debian, using firefox, with a dark theme in debian I still get the same colours as the image I previously posted in this thread

**Comment by a16hiwah** [comment] 2019-05-06 10:08
@b17timjo I tested it on debian 9 , using firefox, with a dark theme and got the following result.

![20190506_114918](https://user-images.githubusercontent.com/37792852/57219186-8de96800-6ff7-11e9-959f-a263b8ceb80b.jpg)

**Comment by b17timjo** [comment] 2019-05-06 10:10
It could be limited to Firefox ESR, I suppose

**Comment by a16hiwah** [comment] 2019-05-06 12:02
I use both  Firefox ESR , debian 9  and  get the same colours as the image I previously posted.

**Comment by b17timjo** [comment] 2019-05-06 12:07
Then it is probably related to the version in debian stable. I would say we can close this then. @b17nicsv

**Comment by c17johha** [comment] 2019-05-06 13:27
![image](https://user-images.githubusercontent.com/49199825/57228113-51c40080-7013-11e9-8c2a-e1acc51fdb51.png)

This is what I get in Debian, Gnome, Firefox. Does it fulfill the requirements?

**Comment by b17nicsv** [comment] 2019-05-06 13:44
This looks like an issue only occuring for b17timjo and very hard to replicate. I'll close this for now.

**Closed by b17nicsv** 2019-05-06 13:44 UTC
Labels: GruppB2019, activeGruppB2019
