### ISSUE TITLE
Codeviewer Parenthesis Written Twice

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1734] opened 2015-05-27 11:21 UTC
In example 8, parenthesis after functions are some times written twice (might occur in several examples). Example function() becomes function()().

**Comment by b14davbo** [comment] 2016-05-09 09:36
@HGustavs what is example 8?

**Comment by a17vikab** [comment] 2019-04-16 12:30
To be able to work on this issue, the #5988 needs to be solved.

**Comment by a17andby** [comment] 2019-05-17 13:13
Have tried to recreate this issue by checking different types of files on the CodeViewer. I can't reproduce that parenthesis are written twice.

My suggestion is that we close this issue and if we stumble on this issue again we could just reopen this issue.

**Comment by a17alevu** [comment] 2019-05-17 13:21
Closing this issue.

**Closed by a17alevu** 2019-05-17 13:21 UTC
Labels: CodeViewer, On-Hold, gruppC2019
