### ISSUE TITLE
UML lines change appearance on zoom

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6392] opened 2019-04-29 09:11 UTC
The appearance should be concurrent and not change when zooming in or out
On zoom 100%
![umlLineOriginalAppearance](https://user-images.githubusercontent.com/49199690/56886453-5ca8ef00-6a6f-11e9-9e64-c74130eac693.JPG)
On Zoom +- 10%
![umlZoomAppearance](https://user-images.githubusercontent.com/49199690/56886499-6e8a9200-6a6f-11e9-92b5-aa08b44898c1.JPG)

**Comment by a17jonro** [comment] 2019-04-30 07:50
This also seems to happen when just moving in the canvas.

**Comment by a17johpe** [comment] 2019-05-06 07:47
Duplicate of https://github.com/HGustavs/LenaSYS/issues/6452: "UML Line stops working when zooming in/out, or moving camera"

**Comment by a16tobfr** [comment] 2019-05-27 13:02
Issue can be closed, not a problem anymore.

**Comment by a17vikab** [comment] 2019-05-27 13:20
Solved.

**Closed by a17vikab** 2019-05-27 13:20 UTC
Labels: Diagram, gruppA2019
