### ISSUE TITLE
Code Viewer:  Dropdown list

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1689] opened 2015-05-26 11:50 UTC
It would be nice if there is a dropdown list that presented all the playlinks in the edit example.

**Comment by a15andau** [comment] 2017-04-06 07:00
![screenshot 2017-04-06 kl 08 45 40](https://cloud.githubusercontent.com/assets/26709847/24741546/b2cfea84-1aa6-11e7-9ad9-1f6f6316239c.png)

Do you know the purpose with the play links @HGustavs ? As you can see in the image I've done a dropdown list but I'm not sure what they want the play link to do when Save is clicked. The issue is rather old too so it might not be topical anymore?

**Comment by a17poner** [comment] 2019-05-20 11:06
The playlink dropdown has already been added and currently exists, closing.

**Closed by a17poner** 2019-05-20 11:06 UTC
Labels: CodeViewer, Fix later, gruppC2019
