### ISSUE TITLE
Markdown image zoom rollover

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1960] opened 2016-04-01 21:51 UTC
I would like to have some kind of support for something like the images in this page in the markdown

http://wwwlab.iit.his.se/gush/ShaderprogrammeringOld/Assignment3.html

When we rollover the image it is shown in its original size but normally it is only a thumbnail.

This way it is easier to follow the layout of the page, without it being cluttered with large images.

**Comment by a14jimso** [comment] 2016-04-11 12:37
The issue is now fixed. Support for a really fancy rollover function in both showdoc.php and markdown.js. You'll love it. ;)

**Closed by a14jimso** 2016-04-11 12:37 UTC
Labels: Group-2, lowPriority, Markdown
