### ISSUE TITLE
DuggaEd: Double FABs

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6518] opened 2019-05-02 09:48 UTC
Two FABs show up in DuggaEd
![doublefab](https://user-images.githubusercontent.com/37792198/57067736-1f8f6780-6cd0-11e9-906d-9d908d14892f.PNG)

**Comment by a17andby** [comment] 2019-05-02 11:52
Where do you find two FABs? I can't reproduce this problem on my test environment

**Comment by a17maxsj** [comment] 2019-05-02 12:32
Seems to be on the test page, can't reproduce this issue either

**Comment by a17joaap** [comment] 2019-05-02 12:42
Duggaed, the test editor. If I inspect the element, the second fab is in the headerContent div

**Comment by a17andby** [comment] 2019-05-03 12:17
(reviewer on https://github.com/HGustavs/LenaSYS/pull/6554) 

Still can't reproduce this issue. I tested to reproduce this on my cellphone (Samsung S7, android), local test environment and the test environment on the test server. But I never get two FABS when I'm on duggaed. Could this be a local issue on your side? Or could you please elaborate more how you reproduce this issue so I can test your code.

**Comment by a17joaap** [comment] 2019-05-03 12:31
I tried looking at it in firefox and the FABs overlap eachother there, so that maybe a reason why you can't see it?

Try it with chrome and see if you get the same results. 

If you still can't see it, try looking at the page source, this is what I get:
![twofabs](https://user-images.githubusercontent.com/37792198/57137331-db739400-6daf-11e9-9722-1f6b8962500d.PNG)

**Comment by a17andby** [comment] 2019-05-03 19:55
Could not get two buttons to show either in Firefox or Chrome. But as your picture show, they are two buttons in the source code, which I also can see, and one button in the source code is enough. I just approved the pull request you did since it solved this issue.

**Comment by a17poner** [comment] 2019-05-06 07:42
Merged i  #6554, closing

**Closed by a17poner** 2019-05-06 07:42 UTC
Labels: gruppC2019
