### ISSUE TITLE
Some generated passwords are not working

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1849] opened 2016-01-20 16:19 UTC
There seems to be a discrepancy between password generated and passwords that the system allows.

**Comment by a14maxry** [comment] 2016-05-10 12:47
do you mean that the generated hash sometimes is not accepted in the database?

**Comment by c14caran** [comment] 2017-05-02 09:23
Is this issue still relevant?
The code in dugga.js is currently:
```javascript
function randomstring()
{
//		str="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890![]#/()=+-_:;.,*";
		str="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890";

		var valu="";
		for(i=0;i<9;i++){
				valu+=str.substr(Math.round(Math.random()*78),1);
		}

		return valu;
}
```
While this is not a very good implementation ( the 78 should be replaced with the new str length, currently it produces shorter than 9 length passwords ) it should never give a password that is invalid.

**Comment by c14caran** [comment] 2017-05-09 09:22
@HGustavs Is this issue still relevant?

**Comment by a16seplu** [comment] 2018-04-17 07:47
Is this issue still relevant or should i close it?

**Comment by a16chrsa** [comment] 2018-04-19 07:50
This issue has been solved. Based this on #3469 and #3470 where it has been corrected and tested to work. As intended, generated passwords are not less than 9 characters long.

**Closed by a16chrsa** 2018-04-19 07:50 UTC
Labels: Group 1 (2018), Group 1 (2018) Access, Password
