### ISSUE TITLE
Some codeviewer templates seem wrong

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7782] opened 2020-03-26 19:48 UTC
Some of the rightmost codeviewer templates seem wrong....

when filled with content the content does not scroll right if large
erroneous scrollbars appear to the right

**Comment by HGustavs** [comment] 2020-04-03 13:32
for me it looks like the iframes on previews are slightly oversized.

**Comment by HGustavs** [comment] 2020-04-03 13:33
Could not replicate other errors.

Seems like the iframe is 99% 100% for some reason.

On my laptop screen this is over-sized and there is un-necessary scrollbars.

**Comment by a16vikva** [comment] 2020-04-14 11:58
We've not been able to replicate this issue, or even understand what this issue is about. So more information will be needed, or a screen shot of what the issue is.

**Comment by a18geoge** [comment] 2020-05-05 11:26
I'm not sure what the problem(s) is/are although I think I get what the issue is with the iframe when viewing a preview. I can also agree that if scrollbars aren't needed there is no point for them to exist (when viewing examples with few rows), which I assume is what you are talking about? This type of scrollbar problem appears in every template except the tenth because the issue seems to be that the first box has a correctly working scrollbar and it is the other boxes that have the problem. The problems from the first comment on this issue I was not able to replicate.

See:

![template9iframewrongnotscrollbar](https://user-images.githubusercontent.com/62876595/81060850-978c0100-8ed3-11ea-8303-337fe19cb8a4.jpg)
![template10iframewrongbutnotscrollbar](https://user-images.githubusercontent.com/62876595/81060860-9a86f180-8ed3-11ea-8888-65832683d988.jpg)

**Comment by a18filkr** [comment] 2020-05-14 09:22
The scrollbars have been fixed but the issues with iFrames doesn't seem to be a necessary fix and we are not sure this is even an issue that solves anything. Closing this now as we can't do more than that.

**Closed by a18filkr** 2020-05-14 09:22 UTC
Labels: Bug, CodeViewer, Group-1-2020
