### ISSUE TITLE
Group dropdown does not display under some circumstances

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#5599] opened 2018-08-15 16:52 UTC
In access editor.

1. If you click on a group dropdown it will show as advertised
2. * If you click on the same dropdown _without making any change_
    * Click on any other group dropdown
3. The drop down will disappear but you cannot open any new group dropdown

**Workaround:** If you click outside of the group dropdowns you get out of this problem and can select and show group dropdowns once more.

**Comment by c14jonfr** [comment] 2020-04-07 09:03
I believe this is caused by the expanded variable not being set back to false properly when the dropdown is closed but I'm not 100% sure yet. Looking into it.

**Comment by c14jonfr** [comment] 2020-04-07 09:57
I have come up with a solution of sorts, or at least making progress towards one. Removing row 606 lets the user open, close and edit the Group-column as expected. This does however create a new issue.. 

If one of the Group dropdowns are open and the user clicks one of the other dropdowns (Class, Examiner etc.) these dropdowns will not be opened properly (just like the group dropdowns bugged out before). 

**Workaround:** If the user opens and closes one of the group dropdowns properly (by clicking the dropdown again or clicking somewhere outside of it (somewhere that isn't one of the other dropdowns of course) all of the dropdowns can be interacted with properly.

**Comment by c14jonfr** [comment] 2020-04-07 12:11
Some more progress: I am pretty sure the if statement in the mouseUp-function(_if (expanded && !checkboxes.contains(e.target))_) is causing the issue. This seems to always turn out to be false (regardless of what element is clicked). When the dropdown menu is opened and then closed by clicking it again, both the code inside the if statement in mouseUp and showCheckboxes are run at the same time causing the buggy behaviour.

**Comment by c14jonfr** [comment] 2020-04-08 06:57
Update on progress: changing the if statement in mouseUp() (row 598)  to _if (expanded && e.target.parentElement != activeElement)_ makes the behaviour somewhat more in line with what is expected. 

The user can open and close the group-dropdowns and it will not bug out. However if the user opens one of the dropdowns and then clicks another of the group dropdowns (without closing the first one) the dropdowns will bug out and behave just like before any change. 

There is also a small issue when opening a group dropdown and then clicking a dropdown in one of the other columns, this will make the "new" dropdown open and close once very fast but it does not bug out beyond that (they can be opened and closed and edited etc without issue). This does not seem to be an issue I have introduced, it seems to be in line with the behaviour before any change. Therefore I will not bother trying to fix that issue here but rather make a new issue concerning that behaviour.

**Comment by c14jonfr** [comment] 2020-04-08 10:03
We (@b18jonli and myself) have come up with a solution for part of the issue. Our solution fixes the problem where opening a dropdown without making changes will make the dropdowns bug out.

The issue that is still there is the one where you open a dropdown and then click another dropdown (in the group column) without closing the first will make the dropdowns bug out. 

We will open a pull request that will close this issue and create a new issue for the bug that is still there.

**Comment by b18alegu** [comment] 2020-04-14 05:44
Issue solved last week (W15 2020). I'm now closing this issue.

**Closed by b18alegu** 2020-04-14 05:44 UTC
Labels: AccessED, Group-2-2020, bug
