### ISSUE TITLE
Implement darkmode based on the mockup

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11725] opened 2022-04-20 13:26 UTC
We may not implement the mockup which was created in the #11449 issue. This is only the case for the codeviewer, and not for other parts of lenasys for this issue.

DO NOT WORK ON THIS ONE UNTIL #11724 IS DONE.

**Comment by a20sarle** [comment] 2022-04-22 06:48
Duplicate of issues. See #11449 and #11724. Closing issue.

**Closed by a20sarle** 2022-04-22 06:48 UTC
Labels: Group-2-2022, on hold
