### ISSUE TITLE
Touch: Adding a new item in sectioned.php on a touch screen creates two items.

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6054] opened 2019-04-17 11:38 UTC
When using any touch screen to add a new item in sectioned.php, two items are created instead of just a single item. Please fix.

**Comment by a17maxsj** [comment] 2019-04-18 07:36
touchend touchstart something something

**Comment by a17maxsj** [comment] 2019-04-18 11:38
This can be tested using the Toggle device toolbar in dev mode

**Comment by a17alevu** [comment] 2019-04-18 12:57
Yes this sounds good, the only problem it causes a new issue.

**Comment by a17maxsj** [comment] 2019-04-26 11:39
Any news on this?

**Comment by b17carma** [comment] 2019-04-29 09:39
Can't reproduce this problem with the latest version, might have been fixed with https://github.com/HGustavs/LenaSYS/issues/6340

**Comment by a17maxsj** [comment] 2019-04-29 11:59
This is working. Closing...

**Closed by a17maxsj** 2019-04-29 11:59 UTC
Labels: gruppC2019
