### ISSUE TITLE
Lack of foreign key in the database

### ISSUE THREAD

**Issue by b14kriwe** [HGustavs/LenaSYS#2412] opened 2016-05-27 12:13 UTC
In the database there is a lack of foreign key constraints. This can be a problem when data is being updated, deleted, and inserted. Without a constraint data can be changed that effect other data in the db and rendering it useless. An example here is the the different versions of things in the database does not use foreign keys.

**Comment by a15freed** [comment] 2017-04-05 12:32
This issue seems to broad, needs to specify more what the problem is. Closing for now.

**Closed by a15freed** 2017-04-05 12:32 UTC
Labels: SQL
