### ISSUE TITLE
Identify and edit service files to support test API

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13679] opened 2023-05-03 10:06 UTC
Related to: #13631 and #13532

Uid value is empty when using test API callServiceTest(). Identify best approach to solve this problem. Discussed solutions so far:

Set userid after checkLogin() (CheckLogin sets SESSION uid)
````
if(checkLogin()){

	if(isset($_SESSION['uid'])){
		$userid=$_SESSION['uid'];
	}else{
		$userid="UNK";
	}
````

Another solution might be to add function in `sessions.php` that returns uid
````
if(checkLogin()){
	$userid=postUid();
````	

All service files that needs to be tested have to be changed.

**Comment by b21kurar** [comment] 2023-05-03 13:30
`courseedservice.php`:
The userid is set in the beginning of the file by accessing `$_SESSION['uid']`. For the test API this isn't possible, since it won't be set before accessing the service. The userid could instead be set **after** checking the login. Which will allow the service to use the correct userid regardless if it is called by the test API or in normal usage.

Rather than changing where the userid is set, it is a simpler solution to just add the same check directly after checking the login, effectively doing the same thing twice. This is because the userid is used before this point, as such adding this will not break anything else.

**Comment by b21kurar** [comment] 2023-05-03 16:48
`accessedservice.php`:
`$userid` is used for logging (but also for determining `$hasAccess`, accessed by SESSION
`$uid` is used for the service, accessed by POST

**Comment by b21kurar** [comment] 2023-05-05 09:58
When trying to access `accessedservice` it gives either crashes or gives an error. In the web server:
![image](https://user-images.githubusercontent.com/129070844/236428491-185f62a8-7d8f-4e05-893d-09e86307dbce.png)

On a local server (could be a problem with my config however):
![image](https://user-images.githubusercontent.com/129070844/236428579-4c110ba1-2d43-4506-ab95-226726cc2411.png)

This is the line of code specified in the second screenshot:
`$query = $pdo->prepare("SELECT /*user.firstname*/,user.uid, /*user.lastname*/ FROM user, user_course WHERE user_course.access = 'W' AND user.uid=user_course.uid GROUP by /*user.firstname,user.lastname,*/ user.uid /*ORDER BY user.firstname, user.lastname;*/");`

**Comment by b21kurar** [comment] 2023-05-05 09:59
It also sends `GET` via `$opt`, however the code in `accessedservice.php` doesn't have functionality for `GET`

**Comment by b21kurar** [comment] 2023-05-05 10:41
Since I can't get `accessedservice` to work in normal usage, I will wait with it. Is this file still intended for use in the system?

**Comment by c21alest** [comment] 2023-05-08 08:43
> Since I can't get `accessedservice` to work in normal usage, I will wait with it. Is this file still intended for use in the system?

It looks like the function to create users is unused at the time being

**Comment by b21kurar** [comment] 2023-05-08 10:14
`showDuggaservice.php`
Trying to work out why the response is different when calling via the test API vs normal usage. 
Parameters sent:
![image](https://user-images.githubusercontent.com/129070844/236798320-e2ff49fe-3580-4bd6-9668-fc8348eb1084.png)


Expected out:
![image](https://user-images.githubusercontent.com/129070844/236798415-0d13b1f5-8f36-45db-810c-885190ab646d.png)

Service out:
![image](https://user-images.githubusercontent.com/129070844/236798486-0dfbeb9e-ec29-4466-9f97-0c891be4eeaf.png)

**Comment by b21kurar** [comment] 2023-05-08 10:19
One problem I have identified is that there is a `password` parameter sent with the payload to the service 
![image](https://user-images.githubusercontent.com/129070844/236798788-c8937204-9684-4c10-a466-8fa355f85e48.png)

This would require that two different values are set in the same place in the API's `service-data`:
![image](https://user-images.githubusercontent.com/129070844/236799069-4bd00e7f-99ac-4f1d-afd5-b630ed51455d.png)

![image](https://user-images.githubusercontent.com/129070844/236799248-c0ea523f-57ba-4de9-87b7-6e6346d2246e.png)


This doesn't work for obvious reasons, either the logging in won't work or the hash password won't get the right value.

**Comment by b21kurar** [comment] 2023-05-08 10:20
One proposed change is to update the API to separate the user login to a separate array, as such conflicting names will be in different parts and hopefully won't intefere with each other.

**Comment by c21alest** [comment] 2023-05-08 10:25
Agree!

**Comment by c21alest** [comment] 2023-05-08 10:30
After some investigation it looks like sessions.php uses username and password from POST which is the data in service-data sent by the Test API, so it needs to be included in the array.

**Comment by b21kurar** [comment] 2023-05-08 12:13
Alright, I thought that `loginTest()` would handle all logging in functionality but then it would mean that it is the service calling the login function?

**Comment by c21alest** [comment] 2023-05-08 12:19
The login in session.php is suppose to remember the login with cookies but this is not working, and I dont think cookies would have helped (we had problems with SESSION also). When callService test runs the service file checks if user is signed in, and it will return false because it's not remembered from loginTest. That's why the login credentials are needed to be POST:ed again in callService test. Do you understand what I mean?

**Comment by b21kurar** [comment] 2023-05-08 12:19
This could maybe work?
```php
sessions.php

//------------------------------------------------------------------------------------------------
// checklogin
//------------------------------------------------------------------------------------------------
// checks against session to see if we are logged in
//------------------------------------------------------------------------------------------------

function checklogin()
{   
      // If neither session nor post return not logged in
      if(array_key_exists('loginname', $_SESSION)){
        return true;
      } else if(failedLoginCount($_SERVER['REMOTE_ADDR']) < 100 && array_key_exists('username', $_COOKIE) && array_key_exists('password', $_COOKIE)) {
        return login($_COOKIE['username'], $_COOKIE['password'], false);
      } 

      // Test API uses POST
      else if(failedLoginCount($_SERVER['REMOTE_ADDR']) < 100 && array_key_exists('username', $_POST) && array_key_exists('password', $_POST)) {
        $usr = 'username';
        $pwd = 'password';
        if(isset($_POST['login-usr']) { $usr = 'login-usr'; }
        if(isset($_POST['login-pwd']) { $pwd = 'login-pwd'; }
        return login($_POST[$usr], $_POST[$pwd], false);
      }
      else {
        return false;
      }
}
```

**Comment by c21alest** [comment] 2023-05-08 12:22
Im not sure if variable values are saved between tests ($usr, $pwd), can you confirm this is working?

**Comment by b21kurar** [comment] 2023-05-08 12:48
> Im not sure if variable values are saved between tests ($usr, $pwd), can you confirm this is working?

I tested it, but it doesn't work. Since the service calls `checklogin()` (which in turn calls `login()`) will still look for the user credentials via `getOP()` and as such would require that all services change this.

A simpler solution could be updating the only `showDuggaservice.php`  so that the conflicting variables are updated, possiby?

**Comment by c21alest** [comment] 2023-05-08 13:36
Looked at your suggested code again and now I understand the problem. Then I agree changing to login-**** in session.php

**Comment by b21kurar** [comment] 2023-05-08 13:43
I tried that, but it still didn't really work. I might have missed something. I think that since the service handles the login call by itself it will conflict either way. A way around it would be changing where the conflicting variable accesses the `$_POST` value.
![image](https://user-images.githubusercontent.com/129070844/236839990-6df0aae9-84ce-4f16-87f3-9b7b5391cff5.png)

However I am not sure what repercussions this would have, as I can't track down where this value gets set during "normal" LenaSYS usage.

**Comment by b21kurar** [comment] 2023-05-08 14:02
This is the payload sent from normal usage 
![image](https://user-images.githubusercontent.com/129070844/236844669-a558e4e7-763b-4752-89e6-8b1ee1753174.png)

**Comment by b21kurar** [comment] 2023-05-08 14:08
**From test API**
Expected: 
![image](https://user-images.githubusercontent.com/129070844/236845229-0456784a-1917-4530-a403-8edafe688c6b.png)
Actual:
![image](https://user-images.githubusercontent.com/129070844/236845303-339dd696-4d0c-4f01-9f7e-08937dab7e69.png)

The `debug` value returned from the actual output is confirmed to be set in lines 440 - 448 in `showDuggaservice.php`, where the condition for this is the else part of the following if statement
```php
if(	isset($_SESSION["submission-$courseid-$coursevers-$duggaid-$moment"]) && 
					isset($_SESSION["submission-password-$courseid-$coursevers-$duggaid-$moment"]) && 
					isset($_SESSION["submission-variant-$courseid-$coursevers-$duggaid-$moment"])){```
					
This makes me believe that the `$_SESSION` values aren't set. This must be the problem with using the API

**Comment by b21kurar** [comment] 2023-05-08 14:12
`profileservice` and `highscoreservice`  will be skipped as they where declared as low prio according to following comments:
https://github.com/HGustavs/LenaSYS/issues/13240#issuecomment-1506863338

https://github.com/HGustavs/LenaSYS/issues/13241#issuecomment-1506861751

**Comment by b21kurar** [comment] 2023-05-08 14:41
`resultedservice` and `sectionedservice` both needed to re-check `$_SESSION['uid']` after a checking log in.

**Closed** 2023-05-10 09:17 UTC
Labels: Group-2-2023
