### ISSUE TITLE
sectioned.php: new instance -> database does not match expected structure?

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5650] opened 2019-04-04 16:12 UTC
When setting up a new instance of lenasys, with test data, upon visiting a course site the following alert pops up:
![sectioned_newinstance_error](https://user-images.githubusercontent.com/38911528/55570898-b1717800-5704-11e9-890c-6fffe8e31ab9.png)

See: sectionedservice.php
Possible cause: newly created database does not match what the queries expect?

**Comment by a17adajo** [comment] 2019-04-05 06:58
This does not happen in the production Environment.
How can we assert that a freshly created database by the install script matches the production Environment at all times?

**Comment by a17adajo** [comment] 2019-04-05 07:03
I will do some trubleshooting on this today

**Comment by a17adajo** [comment] 2019-04-05 07:31
This issue is somewhat a duplicate of #5641

**Comment by HGustavs** [comment] 2019-04-05 08:25
This is due to the discrepancy between the init_db run by the installation script and the init_db in the shared sql folder?

Question is if they have diverged further or if this is the only difference?

**Comment by HGustavs** [comment] 2019-04-05 08:26
Main solution to this is to delete the sql file in the installation script and link the installation script to the sql file and ... synchronizing the two files before deleting the former.

**Comment by a17joaap** [comment] 2019-04-05 12:01
The SQL file 'deltachange.sql' adds groupKind column to listentries. Add deltachange.sql to installation script?

**Comment by a17adajo** [comment] 2019-04-05 12:34
deltachange.sql can not be run in its current form. There are stuff like:

_mysql> ALTER TABLE groups MODIFY groupKind VARCHAR(8);
Query OK, 0 rows affected (0.12 sec)
Records: 0  Duplicates: 0  Warnings: 0_

**Comment by a17adajo** [comment] 2019-04-05 12:36
This issue is mostly the same as #5657

**Comment by b17carma** [comment] 2019-04-05 13:11
Not a solution but you can get the site to work properly by looking at the SQL scripts and manually adding the missing columns through something like phpmyadmin if you're running the system locally (there are quite a few fields you have to add however).

**Comment by b17carma** [comment] 2019-04-05 13:35
Possible solution? https://github.com/HGustavs/LenaSYS/commit/8bd55543390f1654733d8692aba4d5433ece3c5

**Comment by b17timjo** [comment] 2019-04-05 14:08
Example subset of diff between install/sql/init_db.sql and shared/sql/init_db.sql.

Notice shared/.. uses a hard-coded database, install/ sets the database when connecting, see:
install.php (starting at line 664) wchich sets up the db connection with $databasename (as set in coursesyspw.php? at line 683)

![kdiff](https://user-images.githubusercontent.com/38911528/55633219-2784e600-57bc-11e9-81a8-4956d344c62b.png)

**Comment by a17joaap** [comment] 2019-04-05 16:59
Created a [pull request](https://github.com/HGustavs/LenaSYS/pull/5687) for @b17carma 's solution which solves this issue, also included a fix for the error during installation which increases the volume of test data.

Tested this on a fresh LenaSYS installation in a Docker container, working flawlessly.

**Comment by a17joaap** [comment] 2019-04-18 20:21
Fixed with #5687

**Closed by a17joaap** 2019-04-18 20:21 UTC
Labels: GruppB2019, bug, gruppA2019, gruppC2019, highPriority
