### ISSUE TITLE
Issue with loading a dugga 

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15158] opened 2024-04-30 09:19 UTC
When trying to load a dugga (using the button) with a hash and password, a redirect is stopped because of a echo used to print an error in _basic.ph0p_ line 34. Don't know why the error occurs, but commenting it out makes it possible to actually load a dugga.

**Comment by a22marca** [comment] 2024-04-30 09:50
When loading a dugga using a  hash there are a some redirect being made, to validateHash.php and the dugga itself, e.g.
`http://localhost/LenaSYS/sh/?s=d9fd2fa5`. The last redirect seems to be stopped because of a `echo` (these stops redirects). The echo is made by a custom error function declared in basic.php.
```
function customErrorHandler($errno, $errstr, $errfile, $errline) {
	$refer = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";

	// if this is a service, file don't return anything. This solution is not good, as this should not be nessesary, errors should instead be resolved.
	if (strstr(strtolower($refer), 'service')) { 
		return;
	}

    switch ($errno) {
		case E_USER_ERROR:
			echo '<script> alert("
									ERROR: ['.$errno.'] '.$errstr.'\n
									Fatal error on line '.$errline.' in file '.$errfile.'\n
									PHP ' . PHP_VERSION . ' (' . PHP_OS . ')
								"); 
				</script>';
			exit(1);
			break;

		case E_USER_WARNING:
			echo '<script> alert("WARNING: ['.$errno.'] '.$errstr.'"); </script>';
			break;

		case E_USER_NOTICE:
			echo '<script> alert("NOTICE: ['.$errno.'] '.$errstr.'"); </script>';
			break;

		default:
			echo '<script> alert("Unknown error type: ['.$errno.'] '.$errstr.'\n error on line '.$errline.' in file '.$errfile.'"); </script>';
			break;
    }
}
```

In this case the echo is made because of the default case in the switch statement. It is possible to load the dugga when commenting the echo out. 

First of I need to see if I can find the reason for the error occurring before the redirect.

**Comment by a22marca** [comment] 2024-04-30 09:56
It seems the error is not always occuring. It might be related to duggor in specific courses or a specific dugga.

**Comment by a22marca** [comment] 2024-04-30 10:06
All duggor seems to work to load when logged in as a student. Will proceed to try the same as a teacher.

**Comment by a22marca** [comment] 2024-04-30 11:34
Everything seems to work as at it should. Maybe this issue was caused by something on the branch where the problem was found. Closing the issue for now, and we can reopen it again if this problem should arise again.

**Closed by a22marca** 2024-04-30 11:34 UTC
Labels: Group-2-2024
