### ISSUE TITLE
There is a bug in the system where you can go through the system without being logged in

### ISSUE THREAD

**Issue by a15ramha** [HGustavs/LenaSYS#3358] opened 2017-04-27 07:39 UTC
This bug need to be solved to because the user need to get feedback from the system and the unauthorised users should not have access. This bug is even present in dugga.iit.his.se

**Comment by HGustavs** [comment] 2017-04-27 07:59
Give an example using a screenshot

**Comment by a15ponja** [comment] 2017-04-27 08:40
I was given some more information on the bug and its about that you can enter various courses and duggor/assignments without being logged in. As a point of reference when you look at how the scio site works if you are not registered to a course you can not even see that it exist. Whether  or not this is a bug or feature is something that falls ultimately on @HGustavs

**Comment by a15ramha** [comment] 2017-04-28 09:44
Here is an example where i could go into files without being logged in.
<img width="1280" alt="skarmavbild 2017-04-28 kl 11 43 17" src="https://cloud.githubusercontent.com/assets/26706764/25523689/ee38060c-2c07-11e7-9158-561e8dc48056.png">

**Comment by a15ponja** [comment] 2017-05-03 10:50
So i talked with Henrik about this issue and this is not a bug, however it might be good to have someone try out to see if its possible to get any sensitive information from the system.

**Comment by c14caran** [comment] 2017-05-08 11:57
I have tried to examine all pages and can't find any that give out sensitive information. When navigating manually to some of them when logged out they give nondescriptive error messages or just a blank screen, but nothing private

**Comment by a15timbe** [comment] 2017-05-08 12:00
@HGustavs 

As stated by @c14caran 
> I have tried to examine all pages and can't find any that give out sensitive information. When navigating manually to some of them when logged out they give nondescriptive error messages or just a blank screen, but nothing private

 This doesn't seem to be a problem anymore. Closing this issue.

**Closed by a15timbe** 2017-05-08 12:00 UTC
Labels: bug, Group-2, highPriority, user feedback, user interaction
