### ISSUE TITLE
quotation marks breaks codeviewer

### ISSUE THREAD

**Issue by a14jonal** [HGustavs/LenaSYS#2100] opened 2016-04-12 10:05 UTC
in the codeviewer if you select code view and choose a file with ' or " in them it gives several errors and breaks.

if you upload an xml file containing this code

``` <note>
<to>Tove</to>
<from>Jani</from>
<heading>Reminder</heading>
<body>Don't forget me this weekend!</body>
</note>
```

then the site gives you an error

**Comment by b14davbo** [comment] 2016-04-13 10:47
To solve this we will need to escape all in-data so the quotation mark get's an backslash (\) prepended.

```PHP
<?php
$str = "Don't forget me this weekend!";
echo addslashes($str);

// outputs: Don\'t forget me this weekend!
?>
```

**Comment by HGustavs** [comment] 2016-04-15 09:06
But only for single quotattipn marks right?

Normal strings in code stll works riight?

~~~
var person="Sven";
var annanperson='greger';

var tredjeperson='olle;
var fjardeperson='Boo"Hoo';
~~~

As in this code only the second two are wrong and need to be escaped, right?

Or am I missing something?

**Comment by a14jimso** [comment] 2016-04-18 08:17
https://regex101.com/r/aB4oP9/1

A more visual example of what the issue is. As you can see at the next to last row, it will start capturing the text from the ' in the word don't, which it should not do. So yes, in these cases, one would have to escape the single quotes that appear in each word.

**Comment by a15freku** [comment] 2017-05-02 07:20
Check if this issue is still relevant if it is not then close this issue

**Comment by A15cecal** [comment] 2017-05-03 10:04
I get no errors when I try this. 
Although, when uploading a file with "'" in it's name it looks sort of weird. I tried to upload two files, one with ' and one without (test.xml and test'.xml), and the one with it got the name "testOrderedLists.md", and the one without it got "showdoc-test.md".
@a15freku What should we do? It's kind of connected to this issue but we could also make a new one?

**Comment by a15freku** [comment] 2017-05-03 10:35
Close this issue and make a new one for the other problem you discovered

**Comment by A15cecal** [comment] 2017-05-03 13:52
Closing.

**Comment by A15cecal** [comment] 2017-05-05 18:35
Noticed now that this still actually causes an error but in a different form. I'm opening this again and will look in to it.

**Comment by a15freku** [comment] 2017-05-08 11:34
Solved

**Closed by a15freku** 2017-05-08 11:34 UTC
Labels: CodeViewer, Group-1, highPriority
