### ISSUE TITLE
Error occurs when trying to paste the link to clipboard

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11594] opened 2022-04-13 09:01 UTC
This issue appears only on the server and not when tested locally.

references: #11377 ##11564

**Comment by a17nikjo** [comment] 2022-04-13 09:13
![image](https://user-images.githubusercontent.com/102593975/163140690-d1f121e1-b3de-4120-8936-0a9011b15423.png)

error caused by using navigator which requires secure origin (either HTTPS or localhost).

Will implemented text area method instead.
Which is based around creating a text area with the text to copy, and then using document.execCommand('copy')

**Comment by a20behta** [comment] 2022-04-20 09:51
merged into weekly branch

**Closed by a20behta** 2022-04-20 09:51 UTC
Labels: Group-3-2022, Waiting for merge
