### ISSUE TITLE
DuggaED: Creating tests shouldn't be possible if you don't have access

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5214] opened 2018-05-14 09:02 UTC
At the moment when logging-out in the DuggaEd the table header is visible and the "add" button is still available to press even through the user dosn't have access to this functionality. The test isn't being created due to access restrictions but it still something that shouldn't be allowed.

## These "+" buttons should not be visible when logged out
![loggedoutplusbuttons](https://user-images.githubusercontent.com/37794262/39987918-538457b0-5766-11e8-9574-65b9ba3bc098.JPG)

**Comment by a14isshi** [comment] 2018-05-15 11:29
Seem to work as intended, merged and closed!

**Closed** 2018-05-15 11:29 UTC
Labels: Grupp 3 (2018), Grupp 3 (2018) Dugga-Editor, bug, highPriority
