### ISSUE TITLE
Browser inspector messes up grid

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14327] opened 2024-04-03 14:02 UTC
## Description
The background grid doesn't take up the whole background after closing the browser inspector. Elements can still be placed on the blank area so it's just the grid that's broken. 

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/a88a7263-192d-4f08-9956-e49d6aacd036)
inspector open

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/4d9e81e0-8471-4eaf-81f8-3c15a6a5a6e5)
after closing the inspector

## Job
Find out which browsers it's broken on make sure the grid works properly on all browsers.

**Comment by a22jacka** [comment] 2024-04-03 14:06
Checked a tiny bit more and the grid appears to work properly on chrome but not firefox. Updated job part in issue

**Comment by a21liltr** [comment] 2024-04-05 14:23
Pressing 'G'-key to toggle the grid off then on again after closing the inspection tool "repairs" the grid.

Perhaps a solution can be found using this information.

**Comment by a22solmi** [comment] 2024-04-11 06:46
Cant reproduce after weekly merge

**Comment by a22jacka** [comment] 2024-04-15 07:07
Issue is back so reopened. There is a js event for a window-resize which might help solving this

**Closed** 2024-04-15 07:17 UTC
Labels: G1-2024
