### ISSUE TITLE
sectioned.php buttons and hb menu breaking

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6523] opened 2019-05-02 11:20 UTC
Works in desktop view
![image](https://user-images.githubusercontent.com/49199993/57072039-95013500-6cdc-11e9-85f1-1db8b5009b59.png)

When making the window smaller things start breaking
![image](https://user-images.githubusercontent.com/49199993/57072042-992d5280-6cdc-11e9-877f-324cce4e9fa1.png)

After pressing the hamburger button and then clicking outside of the drop down, all items are removed
![image](https://user-images.githubusercontent.com/49199993/57072086-c24de300-6cdc-11e9-80a3-22e5a7d28bff.png)

**Comment by c17alepe** [comment] 2019-05-02 11:25
![image](https://user-images.githubusercontent.com/38323901/57072371-bf072700-6cdd-11e9-927a-2ad531412996.png)

same goes for mobile view

**Comment by a17maxsj** [comment] 2019-05-02 11:55
related #6530

**Comment by b17nicsv** [comment] 2019-05-08 16:14
@a17adasy Is this still an issue?

**Comment by a17adasy** [comment] 2019-05-09 08:29
@b17nicsv no, the issue is fixed!

**Comment by HGustavs** [comment] 2019-05-10 07:28
Since the buttons are teacher facing I have no problem that they do not display well on mobile.

We do not want teachers to do marking or uploading files etc on mobile as it introduces errors.

**Comment by b17nicsv** [comment] 2019-05-10 11:14
Closing this since it isn't an issue anymore.

**Closed by b17nicsv** 2019-05-10 11:14 UTC
Labels: GruppB2019, Sectioned, activeGruppB2019
