### ISSUE TITLE
Create user in accessed.php gives us 500 error

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5624] opened 2019-02-05 09:07 UTC
Nothing happens as the running system does not produce output on 500.

It is probably not a database issue since database issues should give us $debug error message in alert statement.

Syntax error in php?

![screenshot 2019-02-05 10 06 35](https://user-images.githubusercontent.com/6978801/52262791-c2348600-292d-11e9-96fa-353103b7b988.png)

**Comment by a17alevu** [comment] 2019-04-10 13:18
I dont quite understand the issue ? Am I supposed to watch over the code to see if there is any possible errors? Am i supposed to create a error handler?

**Comment by b17carma** [comment] 2019-04-12 08:55
I'm not entirely sure what the problem is since I am able to add users with that button on my local system

**Comment by a17maxsj** [comment] 2019-04-12 09:00
bump @HGustavs

**Comment by a17maxsj** [comment] 2019-04-29 12:40
This seems to no longer be a feature, closing...

**Closed by a17maxsj** 2019-04-29 12:40 UTC
Labels: bug, gruppC2019, highPriority
