### ISSUE TITLE
Having lines between objects when aligning may result in objects getting stacked

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5785] opened 2019-04-10 12:18 UTC
![linesDestroyTheSplittingOfObjectsWhenAligning](https://user-images.githubusercontent.com/49199690/55877772-3b08c600-5b9b-11e9-91b3-fb69643a13b8.JPG)
When lines has been drawn between objects it may result in objects getting stacked on top of each other when aligning vertically, horizontally, etc..

**Comment by HGustavs** [comment] 2019-04-10 14:47
This is not a bug?

By definition, this is the only way this can happen if the diagram is drawn in this shape, since we only update the y coordinate if the two objects have the same x coordinate they will be stacked.

The work process would rather be selecting all 5 objects and centering those, then selecting the attribute and entity and clicking distribute vertically.

or

Selecting first two entities and the relation and centering those, and then hand moving or vertically distribute the remaining two objects.

**Comment by a17jonro** [comment] 2019-04-17 11:57
The fix in #6014 have changed the behaviour of align so that the spacing works a lot better and if aligning twice in a row (eg. top and then right) the items are spread out according to the align mode and no longer stacked on top of each other.

**Comment by a16jenja** [comment] 2019-04-18 12:39
I agree with the previous comment, this issue seems resolved now and the items does not stack anymore when pressing horizontal or vertical align.

@a17jacsv It is your call if this issue should be closed or not, my recommendation is to close it since the issue is fixed by the fix in #6014

**Comment by a17jacsv** [comment] 2019-04-18 12:41
I agree with you. Consider it closed.

**Closed by a17jacsv** 2019-04-18 12:41 UTC
Labels: Diagram, gruppA2019
