### ISSUE TITLE
When trying to add a new user, the button seems to fail to stay up when hovering over it.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11673] opened 2022-04-19 09:48 UTC
to access the page you need to enter a course and press the lock on the right of the navbar.
![image](https://user-images.githubusercontent.com/80856978/163977216-06669fd4-78f2-4fa8-8c8b-933137ae4873.png)

https://user-images.githubusercontent.com/80856978/163977083-b1bc399f-232a-4c34-982e-048bfbef90b2.mp4

**Comment by c20adael** [comment] 2022-04-19 09:56
This issue might be present everywhere but i have noticed it on multiple sites

**Comment by b20hanwa** [comment] 2022-04-20 11:18
It's the same issue with the fabBtn on both sectioned.php and accessed.php. When hovering over the buttons items appear, but when moving to click on those items they dissappear. 

On sectioned.php you are able to touch/klick on the fabBtn when on a smaller screen, the items then appear and also stays when moving to click on them. You are not able to do this on accessed.php.

**Comment by b20hanwa** [comment] 2022-04-20 11:20
<img width="328" alt="Issue #11673" src="https://user-images.githubusercontent.com/81630271/164219489-3bf503fb-56c5-4897-a69a-b97e841d78f5.png">

This error message appear when clicking fabBtn on sectioned.php and accessed.php.

**Comment by b20jonlu** [comment] 2022-04-20 13:05
The fabBtn appears to have been broken by #merge3 since testing the issue on the branch G3-2022-#merge2 the fabBtn is working as it should. From testing it is possible to get the correct behavior by quickly moving the mouse from the plus sign onto the options displayed above it which could indicate the problem is because the "hitbox" is the wrong size. The css of the fabBtn is decided by the style.css file, This file also had a change to the fab btn css on april 7th which could be the origin of the issue.

**Comment by a20behta** [comment] 2022-04-28 11:34
merged into weekly branch. closing issue

**Closed by a20behta** 2022-04-28 11:34 UTC
Labels: Group-3-2022, Waiting for merge
