### ISSUE TITLE
Problem with selecting object after using right-click-move

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6634] opened 2019-05-06 10:32 UTC
As the title says. After you have moved the "camera" with using right click you can't see the black dotted square you're selecting. See pictures:

![Skärmavbild 2019-05-06 kl  12 28 07](https://user-images.githubusercontent.com/37792795/57220191-ab6c0100-6ffa-11e9-8c20-3429f51b6a11.png)

It works when using "space" instead of right-clicking. You should view this black dotted box:
![Skärmavbild 2019-05-06 kl  12 27 11](https://user-images.githubusercontent.com/37792795/57220199-b6bf2c80-6ffa-11e9-9ab3-26ec890d209d.png)

**Comment by a17drama** [comment] 2019-05-07 12:04
@a17jacsv What browser where you using? I can't reconstruct this issue. I moved and selected and saw the dotted box every time. What am I missing? I tried both Chrome and Edge and it works fine. Maybe it's a fruit problem?

**Comment by a17jacsv** [comment] 2019-05-07 12:08
> @a17jacsv What browser where you using? I can't reconstruct this issue. I moved and selected and saw the dotted box every time. What am I missing? I tried both Chrome and Edge and it works fine. Maybe it's a fruit problem?

Haha! I'm using Chrome and it behaves as I described above. You have to move the "camera" with right-click and then stop moving the "camera". When you have done that you can't see the dotted box. I dont believe it's only a Mac-problem...

**Comment by a17drama** [comment] 2019-05-07 12:24
@a17jacsv Tested on different machines with different browsers (Chrome, Edge, Firefox) without this issue. If we are to solve this we would need to assign it so someone that has a machine from the fruit company. This is the only thing that is different. I can't see the problem on my machine.

**Comment by a17jacsv** [comment] 2019-05-07 13:47
> @a17jacsv Tested on different machines with different browsers (Chrome, Edge, Firefox) without this issue. If we are to solve this we would need to assign it so someone that has a machine from the fruit company. This is the only thing that is different. I can't see the problem on my machine.

Thats weird. I will test it again and show you tomorrow.

**Comment by a17drama** [comment] 2019-05-08 07:31
It's definite now. Fruit problem. Caused by the mouse or the software has to be investigated.

**Comment by a17drama** [comment] 2019-05-08 07:39
Not a fruit issue. This happened on a windows as well but trying to replicate it on my PC is impossible. @c17matjo did it on his PC.

**Comment by c17matjo** [comment] 2019-05-08 08:03
To clarify, I could replicate the issue on my linux laptop

**Closed** 2019-05-23 13:12 UTC
Labels: Diagram, gruppA2019
