### ISSUE TITLE
Filter fields not working properly or does not have a real function.

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6196] opened 2019-04-24 08:36 UTC
![dosomething](https://user-images.githubusercontent.com/37793130/56644782-b038c880-667c-11e9-8651-a54997954ad2.PNG)
Inside results, these options are shown. however nothing really changes when using them. They do not seem to work properly. Is the purpose to filter the content after these?

**Comment by a17pongo** [comment] 2019-04-24 08:58
what is the issue?
Please change the title of the issue to be more clear and short summary of the issue

**Comment by a17adasy** [comment] 2019-04-25 08:47
These inputs are related to the ladexport button, so the options chosen will change the text in the ladexport box that pop ups.

![image](https://user-images.githubusercontent.com/37799016/56722430-5a7d2280-6747-11e9-9284-22668728be9f.png)

**Comment by a17pongo** [comment] 2019-04-25 09:00
This does not seem to be an issue and work as intended, closing this issue for that reason.

**Closed by a17pongo** 2019-04-25 09:00 UTC
Labels: GruppB2019
