### ISSUE TITLE
CodeViewer: Buttons appearing everywhere!

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1011] opened 2015-04-20 12:10 UTC
![buttons](https://cloud.githubusercontent.com/assets/11715479/7229694/f949ce5a-e766-11e4-8b4a-ead3ca56dfde.jpg)
These buttons suddenly appeared, find out where and how they arrived

**Comment by HGustavs** [comment] 2015-04-20 21:45
The error handling is less than ideal....

When looking at the post in firebug I see the following:
```
<br />
<b>Notice</b>:  Undefined offset: 13 in <b>/var/www/html/codesys/cv17/CodeViewer/editorService.php</b
> on line <b>224</b><br />
```
This is due to an error on line 224 that is not propagated to the service as an error.

Ideally this error is propagated to the server which then receives a 5x0 error which is shown as an alert.

so the error is an uncaught exception.

Either the error can be fixed in situ or error handling be added in addition to the fix.

**Comment by HGustavs** [comment] 2015-04-20 21:53
In addition to that fix.... it would be a good idea to also by-default hiding most of those buttons in case there are other similar errors.

**Comment by b13danso** [comment] 2015-04-21 10:08
The error was not on line 224, the problem itself was that the query that collected all before/after-ids was selecting all the exampleids with the same courseid as the set cid, ordering the the output by sectionname and examplename, not by id. The temporary fix for now, because we have different courseids, is to select all data from codeexample and order id by exampleid, this seem to fix the problem and aswell allowing us to navigate with the forward/backwards buttons and dropdown menus on them(by holding down mouseclick).

From:
$query = $pdo->prepare( "select exampleid, sectionname, examplename, beforeid, afterid from codeexample where cid = :cid and cversion = :cvers order by sectionname, examplename;");
$query->bindParam(':cid', $cid);
$query->bindParam(':cvers', $cvers);
$query->execute();

To:
$query = $pdo->prepare( "select exampleid, sectionname, examplename, beforeid, afterid from codeexample order by exampleid");
$query->execute();

**Comment by b13danso** [comment] 2015-04-21 10:20
Note: I think the problem was that the data stored in the database.

Example:
Codeexample: 
exampleid=14, beforeid=13, afterid =14, cid=2
exampleid=13, beforeid=12, afterid =13, cid=2

Query: take out all rows with cid=2 from codeexample
Result: 2 rows.

The rows gets stored in each array and then put into one single array.

The problem here is, because of the afterid/beforeid of these two rows, there isnt any array 12 or 13 or 14, there is only two arrays, 0 and 1. This is the cause of the problem I think, not 100% sure.

**Comment by HGustavs** [comment] 2015-04-21 10:24
Kind-of.

I suspect that there is something more to it... what if we choose a course that does not exist or that the user is not allowe do watch, In that case we must never end up in a state that displays any of the buttons.

**Comment by b13danso** [comment] 2015-04-21 10:30
Yes, that is a known issue for now, I can't find the reason behind it though. For now, it doesn't matter what the courseid is on the url, it will still show the code. Same with the ability to select if an example is public or not, doesnt work for now, will look into it further.
For now, we have this simple solution allowing us to navigate around and use the buttons.

**Comment by b13danso** [comment] 2015-04-21 10:38
If the user is not allowed to view the code or the course doesnt exists, what kind of error(popup?, text?,  error 404? and so on) is suitable to display?

**Comment by c12jenek** [comment] 2015-04-21 11:05
I'd say text that says "This content is not available to you" when lacking the rights and "This content does not exist" when there is no content with that url seems reasonable

**Comment by b13danso** [comment] 2015-04-21 11:09
Roger.

**Comment by a13jorla** [comment] 2015-04-29 10:12
Buttons still appeare when logged in as creator. But not as superuser or not logged in.

**Comment by a13jorla** [comment] 2015-05-26 09:59
This seams not to be an issue any longer. Cause i can not access that screen any more. Closing the issue.

**Closed by a13jorla** 2015-05-26 09:59 UTC
Labels: bug, CodeViewer, highPriority
