### ISSUE TITLE
Login woes

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1846] opened 2016-01-12 09:12 UTC
I cannot get firefox (or any other browser) to learn the password for lenasys.
Is it naming of the elments or something that is militating against the password remembering functionality in the browsers?

**Comment by c14caran** [comment] 2017-04-24 13:22
The problem is that the page is reloaded when the login is successful.
When I removed the window.reload part of the login I got the remember functionality to work.

A way to fix this is to make it more like a real login page by faking a second login:
* Wrap the login part in a <form> that points to the current page
* Replace the window.reload with a proper submit of the form
* Make sure that pressing enter on the fields will run the ajax code, not the new form-wrapper

**Comment by a15tobli** [comment] 2017-04-25 10:37
Solved in #3286, closing issue.

**Closed by a15tobli** 2017-04-25 10:37 UTC
Labels: Group-2, Password
