### ISSUE TITLE
AccessEd: Table hover effects slow and unresponsive in Firefox

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6569] opened 2019-05-03 08:45 UTC
When viewing the Access table in Firefox, the hover effects are slow and unresponsive. Should probably be looked into as it's quite annoying.

**Comment by b16johso** [comment] 2019-05-03 08:50
The table in DuggaEd has the same, or similar hover effects, although they work fine in Firefox. Different implementation? Worth looking into.

**Comment by a17andby** [comment] 2019-05-03 20:02
Couldn't make a big difference between the tables in Firefox and Chrome. You do not have plugins or so in Firefox that can affect this?

Maybe you upload a fancy gifs that shows the difference between Firefox and Chrome on your environment? :)

**Comment by HGustavs** [comment] 2019-05-06 08:02
It is not slow for me at least (Updated Firefox, Latest Mac OSX on macbook pro) ...

**Comment by b16johso** [comment] 2019-05-09 09:50
I've tested this on two different computers and get the same result. Latest Firefox version, no extensions. Not getting this at all on Chrome.

**Comment by b16johso** [comment] 2019-05-09 09:59
Here's a comparison, recorded at 60 fps:

Firefox:
![hoverfirefox](https://user-images.githubusercontent.com/37793460/57444979-a785ec00-7251-11e9-8c89-60310dbfb3cb.gif)

Chrome:
![hoverchrome](https://user-images.githubusercontent.com/37793460/57444993-ad7bcd00-7251-11e9-860c-259738a84eb6.gif)

I don't know how noticeable it is in the recording, but the hover effects lag behind the cursor in Firefox and can't quite keep up with the mouse movement.

**Comment by a17fellu** [comment] 2019-05-10 09:34
Yes can confirm it does lag behind quite a bit actually

**Comment by a17fellu** [comment] 2019-05-10 09:44
**Firefox:**

![firefox gif](https://user-images.githubusercontent.com/49202955/57518227-de730500-7318-11e9-9fab-0c473f4624ca.gif)


**Chrome:**

![chrome gif](https://user-images.githubusercontent.com/49202955/57518255-eaf75d80-7318-11e9-8b3c-1eb87c0e7efc.gif)

**Comment by a17andby** [comment] 2019-05-16 15:12
But is it a problem that really needs fixing? Is it worth the time to try to fix this in other words

**Comment by b16johso** [comment] 2019-05-16 17:32
It's an annoying bug that should ideally be fixed, but it's pretty low priority imo

**Comment by HGustavs** [comment] 2019-05-17 06:42
Not sure that this is fixable, since it seems like a simple graphic effect, but it is in reality quite complicated... and consists of generating and stacking a number of gradients.

I fear that the graphical rendering may be the culprit here, and not the code in itself.

**Comment by HGustavs** [comment] 2019-05-20 06:49
Thinking through this again, it may have to do with the use of operating system widgets in the firefox version, if one wants to test this hypothesis, it is possible to remove all such inputs and see if this is the cause, in that case, it is definitely un-fixable in firefox.

**Comment by b17annni** [comment] 2019-05-29 10:30
Could not make progress on this and and is unsure if it's a problem

**Comment by c14jonfr** [comment] 2020-05-04 13:54
I believe this has been solved by https://github.com/HGustavs/LenaSYS/pull/8737. I can no longer notice much of a difference (if any difference at all) between Chrome and Firefox when it comes to hover effects in the Access Editor. I will look into this a bit more but I'm pretty sure this will be closed soon.

**Comment by c14jonfr** [comment] 2020-05-04 14:06
Me and a few other people have tested this in Chrome and Firefox and compared it to the old version (pre #8737) and everyone agrees the Access Editor feels much snappier now. Closing this.

**Closed** 2020-05-04 14:06 UTC
Labels: Access Editor, Group-2-2020
