### ISSUE TITLE
Left clicking without ctrl does not deselect objects anymore

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6506] opened 2019-05-02 09:18 UTC
Left clicking on an object or on the canvas should deselect all other objects if ctrl is not clicked

**Comment by a17drama** [comment] 2019-05-02 12:50
This issue was caused by a bug with cardinality that got solved and this is fine now. Closing this issue without action.

**Closed by a17drama** 2019-05-02 12:50 UTC
Labels: Diagram, bug, gruppA2019
