### ISSUE TITLE
sorting and filter dropdown, bad position

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#7353] opened 2019-05-21 12:49 UTC
Dropdowns are placed far from the hoverlogo. When moving mouse to the dropdown, the dropdown disappear.
![image](https://user-images.githubusercontent.com/49199825/58097353-773a3800-7bd7-11e9-93f7-d2f6ed29ea28.png)

**Comment by c17johha** [comment] 2019-05-21 12:57
Earlier the position was changed in this pull:
#7172

**Comment by b17nicsv** [comment] 2019-05-21 13:28
Duplicate of #7345

**Closed by b17nicsv** 2019-05-21 13:28 UTC
Labels: GruppB2019
