### ISSUE TITLE
Fileed text in mobile view is not correct

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9758] opened 2020-05-28 08:33 UTC
![untitled](https://user-images.githubusercontent.com/62876507/83118409-9adb6c80-a0ce-11ea-8387-275e815d6485.PNG)

**Comment by a20caros** [comment] 2022-04-04 09:07
@c20adael @a20behta  I want to work on this issue

**Comment by a20behta** [comment] 2022-04-04 09:39
@a20caros Looks good start working

**Comment by a20caros** [comment] 2022-04-04 09:54
<img width="287" alt="image" src="https://user-images.githubusercontent.com/81676918/161519591-0bf01fa5-9e9d-4152-b946-68e99acd981b.png">

The issue is fixed and should be closed

**Comment by c20adael** [comment] 2022-04-05 07:01
closing this issue since it has been resolved

**Closed by c20adael** 2022-04-05 07:01 UTC
Labels: File Editor, Good First Issue, Group-3-2022
