### ISSUE TITLE
Important word highlighting - strings within strings not working

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7669] opened 2019-05-29 09:05 UTC
Consider this line of code:
`var str = "<div class='example'>";`

The word example is a string within a string, and won't be highlighted even if you add it to the important word list.

See this PR for reference https://github.com/HGustavs/LenaSYS/pull/7339

**Comment by a18filkr** [comment] 2020-04-08 08:14
The referenced issue doesn't seem to work properly, only works when 1 word is a string. Fixing that at the same time, will open new issue for the first fix.

**Comment by a18filkr** [comment] 2020-04-08 14:10
![Screenshot_2020-04-08 Validating form data(1)](https://user-images.githubusercontent.com/49142751/78793967-67743f80-79b3-11ea-9276-ce08a9804676.png)

Should work properly now, strings within strings should use SINGLEquotes and the string itself uses double quotes.

**Comment by a18filkr** [comment] 2020-04-08 14:11
Changes to codeviewer.css has to be made to change the colour of the important word to blue. Words that are not important should already be shown as blue.

**Comment by a18filkr** [comment] 2020-04-15 07:30
Final commit is up and a new pull request will be made for the new weekly branch.

**Comment by a18jakme** [comment] 2020-04-15 08:22
Color of a important word in a string is still black, it's better to have it blue when it's in a string?
![image](https://user-images.githubusercontent.com/49142935/79315304-04c6fa80-7f03-11ea-849f-e0ffc0674a9d.png)

**Comment by a18filkr** [comment] 2020-04-15 08:33
Color mentioned by tester should now work as intended.

**Comment by a18jakme** [comment] 2020-04-15 08:37
Issue now solved, String in strings are highlighted and marked. Special characters are not marked as important. 
![image](https://user-images.githubusercontent.com/49142935/79316703-fb3e9200-7f04-11ea-8030-f2a2a63b46fb.png)

Colors are now also solved.
![image](https://user-images.githubusercontent.com/49142935/79316772-190bf700-7f05-11ea-9fd6-545249643ac5.png)

**Closed** 2020-04-15 12:14 UTC
Labels: CodeViewer, Group-1-2020, On-Hold
