### ISSUE TITLE
Error occur when refreshing page and moving mouse where canvas is

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6433] opened 2019-04-30 07:57 UTC
When refreshing the page and moving the mouse, this error seem to occur every time. Should investigate what it is, why it is happening, and if we can fix it.
![errorOnMoveAround](https://user-images.githubusercontent.com/49199690/56947599-f505a900-6b2d-11e9-9291-f0f1ee8ea062.JPG)

**Comment by a17alfcl** [comment] 2019-05-06 13:43
Change browser

**Comment by a17jonro** [comment] 2019-05-09 11:55
I'm not entirely certain but this issue seems fixed. I also had this problem before but i cannot recreate it anymore in the current branch.

**Comment by a16tobfr** [comment] 2019-05-09 13:49
Same here. The error seems to no longer be possible to reproduce.

**Comment by a17vikab** [comment] 2019-05-27 12:59
closing this issue because people have trouble to reproduce the problem.

**Closed by a17vikab** 2019-05-27 12:59 UTC
Labels: Diagram, gruppA2019
