### ISSUE TITLE
Error message in "Edit Item" dialog after changing item type to link

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1313] opened 2015-05-06 09:09 UTC
If i change the item type to link and then back again to any type, the link option remains filled in somehow. In case of illegal characters in this option i get the "llegal characters removed in link" message.

**Comment by HGustavs** [comment] 2015-05-06 09:27
We use the "bug" tag and not bracksts in the issue title.

**Comment by b12erijo** [comment] 2015-05-06 09:32
Noted and changed, thanks!

**Comment by b13alebr** [comment] 2015-05-07 07:33
I think this is fixed after my changes on the "edit item" dialog

**Comment by a13denli** [comment] 2015-05-18 12:14
Seems to be working for me. Can you confirmed, so we can close this issue?

**Closed** 2015-05-19 07:25 UTC
Labels: bug, DuggaSys, lowPriority
