### ISSUE TITLE
Create some basic CSS classes like .left and .right

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2665] opened 2017-04-03 17:05 UTC
For easier aligning using float.

**Comment by HGustavs** [comment] 2017-04-04 07:19
Floats should almost *never* be used.

Floats are for positioning images inside text paragraphs, like images in magazines, any other use of floats should be considered a bug. 

Most use of floats like this breaks when the window/page is resized.

**Comment by HGustavs** [comment] 2017-04-04 07:23
If what one considers styling is in the shape of a table e.g. file list, course list, student list,result list etc we use tables...

Currently we also use tables for layout, since flex is a relatively new development...which did not work in internet explorer or android browser, something that has improved recently, If anything, designing menus using flex instead of tables should perhaps be an issue.... together with removing any use of floats for relocating images in text paragraphs.

http://caniuse.com/#search=flex

**Comment by b15matol** [comment] 2017-04-04 09:34
Hello HGustavs. The idea with this is not so much the floats, but to use basic classes to try and get away from use of inline CSS. However, i think the availability of such .left and .right class could be useful to the project, aswell as a no-float-class that removes float from the HTML objects. I also think it could be useful to have a .bold class, for example, that sets font-weight to bold.

**Comment by a15tobli** [comment] 2017-04-04 10:02
Hello Henke!
Would your suggested method consist of removing the floats from this issue and make a separate issue to rewrite the layout so that no current floats are used? 
Or could this be implemented as of now to make the placement of elements by using the current layout, and then add the issue for rewriting this as something that can be done at a later point? 

The later option would require some extra work in the future, but the classes added could be used right away to add new features in the layout.

**Comment by HGustavs** [comment] 2017-04-04 12:27
Question is how widespread the problem is, I am unsure as to where in the user interface we are talking about.... we first need some kind of triage, then we can work on mitigation.

I would say, that making it easier to use floats is not a solution to anything.

Is this in a menu or more generally used in the interface?

**Comment by a15tobli** [comment] 2017-04-04 17:33
The editors have been using this quite alot it seems. I haven't really looked into how spread this issue is above that, but it appears to be something that's mostly affects them. One example is the current dugga editor that is filled with floats for aligning the content. I'm not sure how big of a task it would be to rewrite those to remove the usage of floats, but that definitely sounds like something that could be added as a new issue.  

Note taken, the css will be fixed so that the float classes are removed before merging the  added classes to the stylesheet.

**Comment by a15tobli** [comment] 2017-04-05 12:59
Closing issue, it was a good idea to add classes for styling, but they have no use and would be too complex to use when each class contains such small amounts of code.

**Closed by a15tobli** 2017-04-05 12:59 UTC
Labels: Group-2
